-- Conéctate a tu servidor Firebird usando la herramienta ISQL o alguna herramienta GUI como FlameRobin
CREATE DATABASE 'C:\Users\cirob\OneDrive\Escritorio\Archivos VSC 2\base de datos\actividad ev ORM\examplePA.fdb'
USER 'sysdba' PASSWORD 'masterkey';

-- Cambiar a la base de datos creada
CONNECT 'C:\Users\cirob\OneDrive\Escritorio\Archivos VSC 2\base de datos\actividad ev ORM\examplePA.fdb'
USER 'sysdba' PASSWORD 'masterkey';

-- Crear una tabla de usuarios
CREATE TABLE usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255),
    email VARCHAR(255)
);

-- Crear un procedimiento almacenado para agregar usuarios
SET TERM ^ ;

CREATE PROCEDURE agregar_usuario (
    nombre VARCHAR(255),
    email VARCHAR(255)
)
AS
BEGIN
  INSERT INTO usuarios (nombre, email) VALUES (:nombre, :email);
END^

SET TERM ; ^
